apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order

spec:
  selector:
    app: order
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order

spec:
  selector:
    matchLabels:
      app: order

  replicas: 1

  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: mhdiqbalpradipta/order_service:latest
          ports:
          - containerPort: 3000
          env:
          - name: PORT
            value: "3000"
          - name: AMQP_URL
            value: "amqp://rabbitmq-service.default.svc.cluster.local:5672"