apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping

spec:
  selector:
    app: shipping
  ports:
  - port: 3001
    targetPort: 3001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping

spec:
  selector:
    matchLabels:
      app: shipping
  
  replicas: 1

  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: mhdiqbalpradipta/shipping_service:latest
          ports:
          - containerPort: 3001
          env:
          - name: PORT
            value: "3001"
          - name: AMQP_URL
            value: "amqp://rabbitmq-service.default.svc.cluster.local:5672"