apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: mhdiqbalpradipta/karsajobs-ui:latest
          ports:
            - containerPort: 8000
