apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
spec:
  selector:
    app: karsajobs-ui
  ports:
    - protocol: TCP
      port: 80 # Port exposed within the cluster
      targetPort: 8080 # Port your app is listening on
      nodePort: 30000  # Node port for external access
  type: NodePort  # Exposes the service externally